#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libestr
Version  : 0.1.11
Release  : 3
URL      : https://github.com/rsyslog/libestr/archive/v0.1.11.tar.gz
Source0  : https://github.com/rsyslog/libestr/archive/v0.1.11.tar.gz
Summary  : some essentials for string processing
Group    : Development/Tools
License  : LGPL-2.1
Requires: libestr-lib = %{version}-%{release}
Requires: libestr-license = %{version}-%{release}

%description
nothing yet

%package dev
Summary: dev components for the libestr package.
Group: Development
Requires: libestr-lib = %{version}-%{release}
Provides: libestr-devel = %{version}-%{release}
Requires: libestr = %{version}-%{release}

%description dev
dev components for the libestr package.


%package lib
Summary: lib components for the libestr package.
Group: Libraries
Requires: libestr-license = %{version}-%{release}

%description lib
lib components for the libestr package.


%package license
Summary: license components for the libestr package.
Group: Default

%description license
license components for the libestr package.


%prep
%setup -q -n libestr-0.1.11
cd %{_builddir}/libestr-0.1.11

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1604618053
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%autogen --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1604618053
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libestr
cp %{_builddir}/libestr-0.1.11/COPYING %{buildroot}/usr/share/package-licenses/libestr/de661089a133637e7051a61c8cbb62e071f16633
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/libestr.h
/usr/lib64/libestr.so
/usr/lib64/pkgconfig/libestr.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libestr.so.0
/usr/lib64/libestr.so.0.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libestr/de661089a133637e7051a61c8cbb62e071f16633
